import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import BackToTop from '@/components/BackToTop';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700', '900']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body className="px-[5%] md:px-[15%] min-[2293px]:px-[5%] w-full block mx-auto max-w-[1920px] bg-light dark:bg-dark text-dark dark:text-light">
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
